name: flutter_yith_track_order
description: This extension package allows show page track order of yith plugin
version: 1.0.0
homepage: https://github.com/Sub6Resources/flutter_html

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  dio: ^5.2.1+1
  url_launcher: ^6.0.17
  collection: ^1.15.0
  flutter_spinkit: ^5.1.0
  flutter_html: '3.0.0-beta.2'
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.3

flutter:
