name: flutter_yith_badge
description: This extension package allows show badge of yith plugin
version: 1.0.0
homepage: https://github.com/Sub6Resources/flutter_html

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  html: '>=0.15.0 <1.0.0'
  flutter_html: '3.0.0-beta.2'
#  flutter_html:
#    path: ../..

  intl: ^0.19.0
  flutter_svg: ^1.1.6
  dotted_border: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.3

flutter:

